import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";

const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "7Y Sua plataforma de comissäo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={`${mulish.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col text-[variable]">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}